### ISSUE TITLE
A little help with wrapping details into a struct fn

### ISSUE THREAD

**Issue by dwhiteddsoft** [bytebeamio/rumqtt#281]
Please be gentle as I am relatively new to Rust. I would like to do something super simple. I wanted to wrap and hide all the rumqttc stuff from the main loop. I tried to create a struct like the below. Yes I know I am hard coding in spots, I am just trying to get anything to work. 
```rust
use core::time::Duration;
use rumqttc::{AsyncClient, EventLoop, MqttOptions, QoS};
use tokio::{task, time};

pub struct MqttClient {
    client_id: String,
    host: String,
    port: u16,
}

impl MqttClient {
    pub fn new(client_id: &str, host: &str, port: u16 ) -> MqttClient {
        MqttClient {
            client_id: client_id.to_string(),
            host: host.to_string(),
            port: port,
        }
    }
    pub async fn start(&mut self) {
        println!("Enter start");
        let mqttoptions = MqttOptions::new("test-1a", "localhost", 1883);
        let (client, eventloop) = AsyncClient::new(mqttoptions, 10);
        client
            .subscribe("hello/world", QoS::AtMostOnce)
            .await
            .unwrap();
    
        for i in 1..=10 {
            client
                .publish("hello/world", QoS::ExactlyOnce, false, vec![1; i])
                .await
                .unwrap();
    
            time::sleep(Duration::from_secs(1)).await;
        }
    
        time::sleep(Duration::from_secs(2)).await;
    }
}
```
The from main I tried to simply execute:
```rust
    let mut mqtt_client = MqttClient::new("test-1a", "localhost", 1883);
    &mqtt_client.start().await;
```
And in this, I get no connection to MQTT at all. Is there some threading or cross channel thing I am missing that is causing this not to work? It makes little sense to me that simply moving the code into a fn on a struct would cause it all to fail :-(

**Comment by de-sh** [comment]
@dwhiteddsoft sorry for the extremely late reply. The reason for this issue seems to be the lack of an `eventloop.poll().await`. We are using the initial poll method to actually start a connection and to send/receive messages over the network. refer [eventloop.rs#L127](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/src/eventloop.rs#L127).

If this solved your doubt, please consider closing the issue. Again, extremely sorry this issue got buried for so long.

**Comment by samfweb** [comment]
Hey @de-sh, I'm in a similar situation - complete beginner to rust and rumqttc, also trying to create a simplified client I can use. I would appreciate any help :)

I'm setting up an Axum to act as a REST proxy to an mqtt server and I'm not sure where I should be calling `eventloop.poll().await`.

I can't call it in the main thread because the tokio runtime yells at me for trying to start a runtime within a runtime.

Should I be starting a new thread just to poll the event loop?

**Comment by henil** [comment]
Feel free to reopen if you have more questions.
