### ISSUE TITLE
using TLS to connect to remote mqtt server

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytebeamio/rumqtt#331]
Hi All,
I am trying the tls/tls2  examples that are present in the example sections of rumqttc. But failed to make them to work, both fail with different reasons. 

tls.rs example fails with "Error = Io(Custom { kind: InvalidData, error: "Broker rejected. Reason = NotAuthorized" })" reason. 
Does it load the certificates that are present in the /etc/ssl/certs?, that's where I have my certificates.
Not really understood how the root_store works.

the tls2.rs fails with reason Error = Network(NoValidCertInChain). But here the certificate is self-signed and does not contain any intermediate certs.

Please let me know how to make them work, appreciate any help here.

Thanks & Regards,
Pradeep

**Comment by de-sh** [comment]
Hi @PradeepKiruvale, I believe you have to generate your own certs, recommend using bytebeam/provision to do this, then you have to include the ca and client certs and key where necessary by un-commenting these [lines](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/examples/tls2.rs#L18..L20).

**Comment by PradeepKiruvale** [comment]
@de-sh I have my own self-signed certs created and use these for connecting to a broker. Since its self-signed certs, there will not be any ca certificate. Any idea how to do it in that case?.

**Comment by tekjar** [comment]
Self signed certificates doesn't mean you don't need a CA. It's just that you are the CA. You still need to validate certificates sent by the server with CA.

**Comment by PradeepKiruvale** [comment]
Thats right. I have all the three fields filled with my certificates as shown below
 let ca = include_bytes!("/etc/ssl/certs/My_CA.pem"); //Broker CA file
//My device certificates and key.
 let client_cert = include_bytes!("/home/rnd/RND/rumqtt/rumqttc/certificate.pem");
 let client_key = include_bytes!("/home/rnd/RND/rumqtt/rumqttc/private-key.pem");

Now when I try running I am getting the below error message
Error = Network(NoValidCertInChain)

**Comment by PradeepKiruvale** [comment]
When I run rumqtt/rumqttc/examples/tls.rs example I get below "Not Authorized" error. I have all my certs and keys at /etc/ssl/certs/. I hope
 client_config.root_store =  rustls_native_certs::load_native_certs().expect("Failed to load platform certificates.");
 read the certs from there.

**Comment by PradeepKiruvale** [comment]
I did try already. It's not working, facing some issues as mentioned here https://github.com/bytebeamio/rumqtt/issues/331#issuecomment-998054983.

**Comment by tekjar** [comment]
Ah Ok!. I've been using this client no problem with our [self signed certificates](https://github.com/bytebeamio/provision). It's very likely that the problem is with your certs. 

1. Probably verify your certificates with openssl
2. Use `provision` tool and see if it's working and then compare your certs

**Comment by PradeepKiruvale** [comment]
@tekjar I feel my certs are fine. Because I use the same certs to connect to the mqtt broker with someother mqtt clients. Its only not working with rumqttc. Still I will look into the provision tool.

**Comment by de-sh** [comment]
Hey @PradeepKiruvale, sorry for the late reply, the issue with why `rumqttc` doesn't work well with regular certs is probably(not fully verified) because of our dependency on `rustls`, which for certain reasons is more _strict_ and requires certain fields to be filled that `provision` takes care of. As for your other questions:
1. The `ca` field of `TlsConfiguratiion` takes the contents of the CA's cert and not the path to any file/folder, you have to read to a string, [e.g. is commented here](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/examples/tls2.rs#L18).
2. This depends on the underlying OS, probably true for most Linux distros, please consider the [code given here](https://docs.rs/rustls-native-certs/0.2.1/src/rustls_native_certs/linux.rs.html#32-55).

Hope this helped you. Happy 2022! 🎊

**Comment by PradeepKiruvale** [comment]
@de-sh Thanks for your reply.  Happy 2022!.

I found that the certs are getting read from /etc/ssl/certs folder. But for some reason, these are rejected by the server to connect.

**Comment by de-sh** [comment]
This might probably be because the CA cert-key pair used to generate the device's native cert was different from the one used to generate the broker's certs. I recommend you use `provision` to generate your certs for both, with a common CA to make sure such issues don't occur.

**Comment by PradeepKiruvale** [comment]
@de-sh I did resolve the issue. Using `set_single_client_cert(cert_chain, key)`  to load the self-signed certificates and key helped to resolve the issue.
