### ISSUE TITLE
question: what's the idiomatic way to write an one shot publisher?

### ISSUE THREAD

**Issue by Jimmy-Z** [bytebeamio/rumqtt#447]
To be specific, the program should collect some info, publish them over mqtt, and then quit, that program will likely be called periodically by cron.

I wrote something like this:
```rust
let (client, mut evl) = mqtt::AsyncClient::new(mqtt_opts, mqtt_cap);
let mqtt_jh = tokio::spawn(async move {
  loop {
    eprintln!("MQTT: {:?}", evl.poll().await);
  };
});

// publish 2 messages

client.disconnect().await.unwrap();
tokio::join!(mqtt_jh);
```

the log I got:
```
MQTT: Ok(Incoming(ConnAck(ConnAck { session_present: false, code: Success })))
MQTT: Ok(Outgoing(Publish(1)))
MQTT: Ok(Outgoing(Publish(2)))
MQTT: Ok(Outgoing(Disconnect))
MQTT: Ok(Incoming(PubAck(PubAck { pkid: 1 })))
MQTT: Ok(Outgoing(PubRel(2)))
MQTT: Ok(Incoming(PubRec(PubRec { pkid: 2 })))
MQTT: Err(MqttState(Io(Custom { kind: ConnectionAborted, error: "connection closed by peer" })))
MQTT: Ok(Incoming(ConnAck(ConnAck { session_present: false, code: Success })))
MQTT: Ok(Outgoing(PubRel(2)))
MQTT: Ok(Incoming(PubComp(PubComp { pkid: 2 })))
MQTT: Ok(Outgoing(PingReq))
MQTT: Ok(Incoming(PingResp))
MQTT: Ok(Outgoing(PingReq))
MQTT: Ok(Incoming(PingResp))
```

So apparently I should probably:
* disconnect after `Ok(Incoming(PubComp(PubComp { pkid: 2 })))`
* break the event loop after `MQTT: Err(MqttState(Io(Custom { kind: ConnectionAborted, error: "connection closed by peer" })))`

Is that correct? it kinda still doesn't feel right to me.

**Comment by henil** [comment]
Ideally you should not poll twice after sending a `disconnect` packet because eventloop currently tries to reconnect after getting any kind of  Error (see https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/src/eventloop.rs#L112-L135). 

And the reason before `PubComp` is because a disconnect requests currently is eagerly evaluated before the `rumqttd`'s router get chance to send those packet. You should only send disconnect packet when you want to immediately disconnect.

```
let (client, mut evl) = mqtt::AsyncClient::new(mqtt_opts, mqtt_cap);


// publish 2 messages
// poll according to QoS level * number of publishes


client.disconnect().await.unwrap();
// polling here you should receive a `ConnectionAborted` you can omit polling here if you want
```
- QoS0 polling once should be fine you will get a pingresp in this case
- QoS1 polling once for each publish message (puback)
- QoS2 polling twice for each publish message (pubrec, pubcomp)

API is still not finalized so any kind of constructive feedback is most welcome :)

**Comment by Jimmy-Z** [comment]
Thanks for the detailed explanation.

I'm afraid I'm not fluent enough in neither mqtt nor rumqtt to give useful feedbacks, AFAIK paho-mqtt returns a token the caller can wait upon.

**Comment by henil** [comment]
feel free to reopen if you have any more questions
